Adding EUI results for EUI check
urbanopt/urbanopt-reporting-gem pull request #35
Opened 2020-12-17 05:11 UTC by rawadelkontar

### Resolves #[issue number here]

### Pull Request Description
add site EUI and source EUI results
 ----> ensure EUI results to be within range

2020-12-18 20:58 UTC, kflemin approved these changes

2020-12-18 21:24 UTC, vtnate approved these changes
tested successfully

2020-12-21 22:01 UTC, vtnate requested changes
@rawadelkontar I found a bug. Will push a commit to fix it

2020-12-22 00:06 UTC, vtnate approved these changes

2020-12-23 21:25 UTC, vtnate commented
@rawadelkontar The post-processor doesn't appear to aggregate the EUI's in `default_scenario_report.json[scenario_report][reporting_periods]`. I think it needs to be picked up by a list somewhere in the post-processor.

2020-12-24 17:22 UTC, merged